// Code generated by protoc-gen-go.
// source: github.com/micro/discovery-srv/proto/discovery/discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/discovery-srv/proto/discovery/discovery.proto

It has these top-level messages:
	ServiceEndpoint
	EndpointsRequest
	EndpointsResponse
	HeartbeatsRequest
	HeartbeatsResponse
	WatchResultsRequest
	WatchResultsResponse
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import discovery1 "github.com/micro/go-platform/discovery/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ServiceEndpoint struct {
	Service  string               `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Version  string               `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Endpoint *discovery1.Endpoint `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *ServiceEndpoint) Reset()                    { *m = ServiceEndpoint{} }
func (m *ServiceEndpoint) String() string            { return proto.CompactTextString(m) }
func (*ServiceEndpoint) ProtoMessage()               {}
func (*ServiceEndpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceEndpoint) GetEndpoint() *discovery1.Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type EndpointsRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Limit   uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *EndpointsRequest) Reset()                    { *m = EndpointsRequest{} }
func (m *EndpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*EndpointsRequest) ProtoMessage()               {}
func (*EndpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EndpointsResponse struct {
	Endpoints []*ServiceEndpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *EndpointsResponse) Reset()                    { *m = EndpointsResponse{} }
func (m *EndpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*EndpointsResponse) ProtoMessage()               {}
func (*EndpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EndpointsResponse) GetEndpoints() []*ServiceEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type HeartbeatsRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	After  uint64 `protobuf:"varint,2,opt,name=after" json:"after,omitempty"`
	Limit  uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *HeartbeatsRequest) Reset()                    { *m = HeartbeatsRequest{} }
func (m *HeartbeatsRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatsRequest) ProtoMessage()               {}
func (*HeartbeatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type HeartbeatsResponse struct {
	Heartbeats []*discovery1.Heartbeat `protobuf:"bytes,1,rep,name=heartbeats" json:"heartbeats,omitempty"`
}

func (m *HeartbeatsResponse) Reset()                    { *m = HeartbeatsResponse{} }
func (m *HeartbeatsResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatsResponse) ProtoMessage()               {}
func (*HeartbeatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HeartbeatsResponse) GetHeartbeats() []*discovery1.Heartbeat {
	if m != nil {
		return m.Heartbeats
	}
	return nil
}

type WatchResultsRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	After   uint64 `protobuf:"varint,2,opt,name=after" json:"after,omitempty"`
	Limit   uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *WatchResultsRequest) Reset()                    { *m = WatchResultsRequest{} }
func (m *WatchResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchResultsRequest) ProtoMessage()               {}
func (*WatchResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type WatchResultsResponse struct {
	Results []*discovery1.Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *WatchResultsResponse) Reset()                    { *m = WatchResultsResponse{} }
func (m *WatchResultsResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchResultsResponse) ProtoMessage()               {}
func (*WatchResultsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WatchResultsResponse) GetResults() []*discovery1.Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceEndpoint)(nil), "ServiceEndpoint")
	proto.RegisterType((*EndpointsRequest)(nil), "EndpointsRequest")
	proto.RegisterType((*EndpointsResponse)(nil), "EndpointsResponse")
	proto.RegisterType((*HeartbeatsRequest)(nil), "HeartbeatsRequest")
	proto.RegisterType((*HeartbeatsResponse)(nil), "HeartbeatsResponse")
	proto.RegisterType((*WatchResultsRequest)(nil), "WatchResultsRequest")
	proto.RegisterType((*WatchResultsResponse)(nil), "WatchResultsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Discovery service

type DiscoveryClient interface {
	Endpoints(ctx context.Context, in *EndpointsRequest, opts ...client.CallOption) (*EndpointsResponse, error)
	Heartbeats(ctx context.Context, in *HeartbeatsRequest, opts ...client.CallOption) (*HeartbeatsResponse, error)
	WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...client.CallOption) (*WatchResultsResponse, error)
}

type discoveryClient struct {
	c           client.Client
	serviceName string
}

func NewDiscoveryClient(serviceName string, c client.Client) DiscoveryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "discovery"
	}
	return &discoveryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *discoveryClient) Endpoints(ctx context.Context, in *EndpointsRequest, opts ...client.CallOption) (*EndpointsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.Endpoints", in)
	out := new(EndpointsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) Heartbeats(ctx context.Context, in *HeartbeatsRequest, opts ...client.CallOption) (*HeartbeatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.Heartbeats", in)
	out := new(HeartbeatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...client.CallOption) (*WatchResultsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.WatchResults", in)
	out := new(WatchResultsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Discovery service

type DiscoveryHandler interface {
	Endpoints(context.Context, *EndpointsRequest, *EndpointsResponse) error
	Heartbeats(context.Context, *HeartbeatsRequest, *HeartbeatsResponse) error
	WatchResults(context.Context, *WatchResultsRequest, *WatchResultsResponse) error
}

func RegisterDiscoveryHandler(s server.Server, hdlr DiscoveryHandler) {
	s.Handle(s.NewHandler(&Discovery{hdlr}))
}

type Discovery struct {
	DiscoveryHandler
}

func (h *Discovery) Endpoints(ctx context.Context, in *EndpointsRequest, out *EndpointsResponse) error {
	return h.DiscoveryHandler.Endpoints(ctx, in, out)
}

func (h *Discovery) Heartbeats(ctx context.Context, in *HeartbeatsRequest, out *HeartbeatsResponse) error {
	return h.DiscoveryHandler.Heartbeats(ctx, in, out)
}

func (h *Discovery) WatchResults(ctx context.Context, in *WatchResultsRequest, out *WatchResultsResponse) error {
	return h.DiscoveryHandler.WatchResults(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0xf9, 0x12, 0xdc, 0xeb, 0x07, 0x50, 0x30, 0x59, 0x66, 0x62, 0x4c, 0xbd, 0x78, 0xa1,
	0x18, 0x24, 0xd1, 0x83, 0x7a, 0xd2, 0xc4, 0x8b, 0x89, 0x11, 0x13, 0xcf, 0x63, 0x74, 0xd0, 0x84,
	0xad, 0xb3, 0x2d, 0x24, 0xfe, 0x69, 0xfe, 0x77, 0x96, 0xad, 0x83, 0xb9, 0x11, 0x3f, 0x6e, 0xdd,
	0xb3, 0xf7, 0x79, 0xf6, 0xeb, 0xb3, 0x17, 0xee, 0xa6, 0x4c, 0xcd, 0x16, 0x63, 0xe2, 0xf1, 0xa0,
	0x1f, 0x30, 0x4f, 0xf0, 0xfe, 0x84, 0x49, 0x8f, 0x2f, 0xa9, 0xf8, 0xe8, 0x49, 0xb1, 0xec, 0x47,
	0x82, 0xab, 0x8c, 0xb6, 0x39, 0x91, 0xf8, 0x8d, 0x73, 0x53, 0xf0, 0x4f, 0x79, 0x2f, 0x9a, 0xbb,
	0xca, 0xe7, 0x22, 0xc8, 0xf8, 0x72, 0x39, 0x89, 0x1b, 0x3f, 0x43, 0x73, 0x44, 0xc5, 0x92, 0x79,
	0xf4, 0x21, 0x9c, 0x44, 0x9c, 0x85, 0x0a, 0x35, 0xa1, 0x21, 0x13, 0xc9, 0x2e, 0x9f, 0x96, 0xcf,
	0xad, 0x95, 0xa0, 0x1d, 0x92, 0xf1, 0xd0, 0xae, 0xc4, 0xc2, 0x31, 0xec, 0x52, 0x33, 0x6d, 0x57,
	0xb5, 0xb2, 0x37, 0xb0, 0x48, 0x6a, 0xc7, 0x23, 0x68, 0xa5, 0x67, 0xf9, 0x42, 0xdf, 0x17, 0x54,
	0xfe, 0x25, 0xf2, 0x00, 0x76, 0xe6, 0x2c, 0x60, 0x49, 0x5e, 0x0d, 0x1d, 0x42, 0x9d, 0xfb, 0xbe,
	0xa4, 0xca, 0xae, 0xad, 0x9e, 0xf1, 0x35, 0xb4, 0x33, 0xa1, 0x32, 0xe2, 0xa1, 0xa4, 0xe8, 0x0c,
	0xac, 0x14, 0x43, 0xea, 0xdc, 0xaa, 0xe6, 0x68, 0x91, 0xdc, 0x6d, 0xf0, 0x13, 0xb4, 0x1f, 0xa9,
	0x2b, 0xd4, 0x98, 0xba, 0x1b, 0x1e, 0x80, 0x0a, 0x9b, 0x18, 0x14, 0xfd, 0x65, 0xd7, 0x57, 0x54,
	0xc4, 0x20, 0xb5, 0xdf, 0x40, 0x86, 0x80, 0xb2, 0x71, 0x86, 0xe4, 0x04, 0x60, 0xb6, 0x56, 0x0d,
	0x0a, 0x90, 0xf5, 0x20, 0x7e, 0x85, 0xce, 0x9b, 0xab, 0xbc, 0x99, 0x36, 0x2c, 0xe6, 0x3f, 0xd4,
	0xf2, 0x3f, 0x96, 0x0b, 0xe8, 0x7e, 0x4f, 0x35, 0x34, 0x36, 0x34, 0x44, 0x22, 0x19, 0x94, 0x06,
	0x49, 0x46, 0x06, 0x9f, 0x65, 0xb0, 0xee, 0xd3, 0x0d, 0x40, 0x43, 0xb0, 0xd6, 0xa5, 0xa2, 0x36,
	0xc9, 0xff, 0x35, 0x07, 0x91, 0x42, 0xe7, 0xb8, 0x84, 0xae, 0x00, 0x36, 0x0d, 0x20, 0x44, 0x0a,
	0xed, 0x3a, 0x1d, 0x52, 0xac, 0x48, 0x1b, 0x6f, 0x61, 0x3f, 0x8b, 0x8b, 0xba, 0x64, 0x4b, 0x27,
	0xce, 0x11, 0xd9, 0x76, 0x27, 0x5c, 0x1a, 0xd7, 0xe3, 0x85, 0xbd, 0xfc, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xd2, 0x1a, 0xd1, 0xe4, 0x30, 0x03, 0x00, 0x00,
}
