// Code generated by protoc-gen-go.
// source: github.com/micro/discovery-srv/proto/discovery/discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/discovery-srv/proto/discovery/discovery.proto

It has these top-level messages:
	HeartbeatsRequest
	HeartbeatsResponse
	WatchResultsRequest
	WatchResultsResponse
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import discovery1 "github.com/micro/go-platform/discovery/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HeartbeatsRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	After  uint64 `protobuf:"varint,2,opt,name=after" json:"after,omitempty"`
	Limit  uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *HeartbeatsRequest) Reset()                    { *m = HeartbeatsRequest{} }
func (m *HeartbeatsRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatsRequest) ProtoMessage()               {}
func (*HeartbeatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HeartbeatsResponse struct {
	Heartbeats []*discovery1.Heartbeat `protobuf:"bytes,1,rep,name=heartbeats" json:"heartbeats,omitempty"`
}

func (m *HeartbeatsResponse) Reset()                    { *m = HeartbeatsResponse{} }
func (m *HeartbeatsResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatsResponse) ProtoMessage()               {}
func (*HeartbeatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HeartbeatsResponse) GetHeartbeats() []*discovery1.Heartbeat {
	if m != nil {
		return m.Heartbeats
	}
	return nil
}

type WatchResultsRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	After   uint64 `protobuf:"varint,2,opt,name=after" json:"after,omitempty"`
	Limit   uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *WatchResultsRequest) Reset()                    { *m = WatchResultsRequest{} }
func (m *WatchResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchResultsRequest) ProtoMessage()               {}
func (*WatchResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WatchResultsResponse struct {
	Results []*discovery1.Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *WatchResultsResponse) Reset()                    { *m = WatchResultsResponse{} }
func (m *WatchResultsResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchResultsResponse) ProtoMessage()               {}
func (*WatchResultsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WatchResultsResponse) GetResults() []*discovery1.Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*HeartbeatsRequest)(nil), "HeartbeatsRequest")
	proto.RegisterType((*HeartbeatsResponse)(nil), "HeartbeatsResponse")
	proto.RegisterType((*WatchResultsRequest)(nil), "WatchResultsRequest")
	proto.RegisterType((*WatchResultsResponse)(nil), "WatchResultsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Discovery service

type DiscoveryClient interface {
	Heartbeats(ctx context.Context, in *HeartbeatsRequest, opts ...client.CallOption) (*HeartbeatsResponse, error)
	WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...client.CallOption) (*WatchResultsResponse, error)
}

type discoveryClient struct {
	c           client.Client
	serviceName string
}

func NewDiscoveryClient(serviceName string, c client.Client) DiscoveryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "discovery"
	}
	return &discoveryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *discoveryClient) Heartbeats(ctx context.Context, in *HeartbeatsRequest, opts ...client.CallOption) (*HeartbeatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.Heartbeats", in)
	out := new(HeartbeatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...client.CallOption) (*WatchResultsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.WatchResults", in)
	out := new(WatchResultsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Discovery service

type DiscoveryHandler interface {
	Heartbeats(context.Context, *HeartbeatsRequest, *HeartbeatsResponse) error
	WatchResults(context.Context, *WatchResultsRequest, *WatchResultsResponse) error
}

func RegisterDiscoveryHandler(s server.Server, hdlr DiscoveryHandler) {
	s.Handle(s.NewHandler(&Discovery{hdlr}))
}

type Discovery struct {
	DiscoveryHandler
}

func (h *Discovery) Heartbeats(ctx context.Context, in *HeartbeatsRequest, out *HeartbeatsResponse) error {
	return h.DiscoveryHandler.Heartbeats(ctx, in, out)
}

func (h *Discovery) WatchResults(ctx context.Context, in *WatchResultsRequest, out *WatchResultsResponse) error {
	return h.DiscoveryHandler.WatchResults(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0xec, 0x17, 0x8d, 0xfa, 0xf8, 0x12, 0x6e, 0x91, 0xa2, 0x0c, 0x08, 0x65, 0xea, 0x52, 0x07,
	0x15, 0x24, 0x16, 0x60, 0x62, 0x60, 0x61, 0x41, 0x48, 0xcc, 0x8e, 0xfb, 0xd2, 0x58, 0x4a, 0x70,
	0xb0, 0x5f, 0x22, 0x31, 0xf3, 0xc7, 0x49, 0x93, 0xd2, 0x04, 0xd2, 0x89, 0xcd, 0x77, 0x7e, 0x77,
	0xbe, 0x7b, 0x86, 0x87, 0xb5, 0xa2, 0x38, 0x0f, 0xb9, 0xd4, 0x69, 0x90, 0x2a, 0x69, 0x74, 0xb0,
	0x52, 0x56, 0xea, 0x02, 0xcd, 0xe7, 0xc2, 0x9a, 0x22, 0xc8, 0x8c, 0xa6, 0x16, 0xd7, 0x9c, 0x78,
	0x75, 0xe3, 0xdd, 0x75, 0xf4, 0x6b, 0xbd, 0xc8, 0x12, 0x41, 0x91, 0x36, 0x69, 0x4b, 0xf7, 0xc7,
	0xa7, 0x56, 0xfb, 0xcf, 0x70, 0xf6, 0x84, 0xc2, 0x50, 0x88, 0x82, 0xec, 0x0b, 0x7e, 0xe4, 0x68,
	0x89, 0x01, 0x0c, 0xd4, 0xca, 0xed, 0x5f, 0xf6, 0xe7, 0x13, 0x76, 0x0c, 0x07, 0x22, 0x22, 0x34,
	0xee, 0xa0, 0x84, 0xa3, 0x0d, 0x4c, 0x54, 0xaa, 0xc8, 0x1d, 0x56, 0xf0, 0x04, 0xc6, 0x3a, 0x8a,
	0x2c, 0x92, 0x3b, 0xda, 0x60, 0xff, 0x06, 0x58, 0xdb, 0xce, 0x66, 0xfa, 0xdd, 0x22, 0xbb, 0x00,
	0x88, 0x77, 0x6c, 0xe9, 0x3b, 0x9c, 0x1f, 0x2e, 0x81, 0xef, 0x06, 0xfd, 0x57, 0x98, 0xbe, 0x09,
	0x92, 0x71, 0x29, 0xc8, 0x93, 0x26, 0xc6, 0x29, 0x38, 0x16, 0x4d, 0xa1, 0x24, 0xfe, 0x2b, 0xcb,
	0x15, 0xcc, 0x7e, 0xbb, 0x6e, 0xd3, 0xb8, 0xe0, 0x98, 0x9a, 0xda, 0x46, 0x71, 0x78, 0x3d, 0xb2,
	0xfc, 0xea, 0xc3, 0xe4, 0xf1, 0x67, 0x41, 0xec, 0x16, 0xa0, 0xe9, 0xc2, 0x18, 0xef, 0xec, 0xc9,
	0x9b, 0xf2, 0x6e, 0x59, 0xbf, 0xc7, 0xee, 0xe1, 0xa8, 0xfd, 0x30, 0x9b, 0xf1, 0x3d, 0xed, 0xbc,
	0x73, 0xbe, 0x2f, 0x9d, 0xdf, 0x0b, 0xc7, 0xd5, 0xcf, 0x5c, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0x83, 0xbc, 0xea, 0x19, 0x02, 0x00, 0x00,
}
